#!/usr/bin/env python3
"""wallpaper_tags.py — character / series / feature tagging for wallpaper names.

Pure-Python, zero dependencies, instant. Works on the konachan-style
underscore filenames used in this repo (e.g. Anime_2B_2b_nier_blue_lily.mp4).

Matching rules:
  - Names are lowercased and split into tokens on "_".
  - A series matches when ANY of its alias phrases is present.
    Multi-word phrases ("jujutsu kaisen") match when every word appears
    as a token (order-insensitive).
  - A character matches when its alias phrase appears in the raw name
    (underscores kept) or all its tokens appear in the token set.
  - "Weak" aliases (very common words like "power", "v") only count when
    another strong alias of the same series is present, to avoid noise.

Usage:
    from wallpaper_tags import tag_wallpapers
    tag_wallpapers("Anime", "Anime_tails_sonic_...jpg")
    # -> {"series": ["Sonic"], "characters": ["Tails"], "tags": [...]}
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Series: display name -> alias phrases (single or multi token, "_" joined)
# ---------------------------------------------------------------------------
SERIES = {
    "Sonic": ["sonic", "tails", "knuckles", "shadow", "amy_rose", "amy",
              "eggman", "rouge", "silver_the_hedgehog", "blaze", "cream_the_rabbit",
              "espio", "charmy", "metal_sonic", "tails_doll",
              "sally_acorn", "scourge", "infinite", "mephiles", "tails_skye"],
    "Jujutsu Kaisen": ["jujutsu", "kaisen", "jjk", "gojo", "satoru_gojo",
                       "sukuna", "itadori", "yuji", "megumi", "fushiguro",
                       "nobara", "kugisaki", "geto", "suguru_geto", "toji",
                       "yuta", "okkotsu", "maki_zenin", "nanami", "kento_nanami",
                       "panda", "inumaki", "rika", "mahito", "hanami", "jogo",
                       "dagon", "choso", "yuki_tsukumo", "mei_mei", "shoko",
                       "ieiri", "kashimo", "higuruma", "takaba", "yorozu",
                       "kamo", "noritoshi", "miwa", "junpei", "yoshino",
                       "yuuji", "satoru"],
    "Chainsaw Man": ["chainsaw", "denji", "makima", "power", "pochita",
                     "aki_hayakawa", "hayakawa", "reze", "kobeni", "himeno",
                     "kishibe", "quanxi", "yoru", "asa_mitaka", "mitaka",
                     "fami", "nayuta", "yuko", "haruka", "katana_man",
                     "violence_fiend", "beam", "angel_devil", "cosmo",
                     "princess", "galgali"],
    "Vocaloid": ["hatsune_miku", "miku", "kagamine", "rin", "len",
                 "megurine_luka", "luka", "meiko", "kaito", "gumi",
                 "ia", "flower", "yukari", "miki", "seeu", "vocaloid"],
    "Touhou": ["touhou", "reimu", "hakurei", "marisa", "kirisame", "cirno",
               "remilia", "flandre", "sakuya", "izayoi", "youmu", "yukari",
               "yakumo", "koishi", "satori", "patchouli", "knowledge",
               "alice", "margatroid", "yuuka", "kazami", "rumia", "chen",
               "ran", "yuyuko", "saigyouji", "sanae", "kochiya", "aya",
               "shameimaru", "hatate", "hina", "kagiyama", "nitori",
               "kawashiro", "momiji", "inubashiri", "letty", "whiterock",
               "lily_white", "sunny_milk", "luna_child", "star_sapphire",
               "seija", "kijin", "shinmyoumaru", "sukuna_shinmyoumaru",
               "tenshi", "hinanawi", "iku", "nagae", "suwako", "moriya",
               "kanako", "yasaka", "kogasa", "tatara", "kisume", "yamame",
               "kurodani", "parsee", "mizuhashi", "sikieiki", "yamaxanadu",
               "komachi", "onozuka", "eiki", "shikieiki", "minoriko", "aki",
               "sister", "shizuha", "hina", "nazrin", "kogasa", "ichirin",
               "unzan", "minamitsu", "murasa", "byakuren", "hijiri",
               "shou", "toramaru", "nue", "houjuu", "kogasa", "kisume",
               "yamame", "kurodani", "parsee", "mizuhashi", "sikieiki",
               "yamaxanadu", "komachi", "onozuka", "eiki", "shikieiki",
               "minoriko", "aki", "sister", "shizuha", "nazrin", "kogasa",
               "ichirin", "unzan", "minamitsu", "murasa", "byakuren",
               "hijiri", "shou", "toramaru", "nue", "houjuu"],
    "NieR": ["nier", "2b", "a2", "9s", "kaine", "kainé", "emil", "devola",
             "popola", "yohra", "adam", "eve", "yoko", "taro", "automata",
             "replicant", "gestalt"],
    "Genshin Impact": ["genshin", "nahida", "raiden", "hutao", "hu_tao",
                       "ganyu", "ayaka", "ayato", "keqing", "fischl", "mona",
                       "klee", "qiqi", "xiao", "venti", "zhongli", "eula",
                       "shenhe", "yae", "yelan", "nilou", "dehya", "furina",
                       "navia", "clorinde", "arleccino", "arlechinno",
                       "neuvillette", "wriothesley", "lyney", "lynette",
                       "freminet", "chiori", "sigewinne", "emilie",
                       "kinich", "mualani", "xilonen", "citlali", "mavuika",
                       "ororon", "chasca", "kokomi", "sangonomiya",
                       "kazuha", "kaedehara", "sayu", "yoimiya", "noelle",
                       "barbara", "lisa", "amber", "sucrose", "diona",
                       "rosaria", "xinyan", "yun_jin", "shenhe", "yunjin",
                       "chongyun", "xingqiu", "xiangling", "beidou",
                       "ningguang", "keqing", "albedo", "klee", "diluc",
                       "jean", "kaeya", "traveler", "lumine", "aether",
                       "paimon", "snezhnaya", "liyue", "inazuma", "sumeru",
                       "fontaine", "natlan"],
    "Honkai: Star Rail": ["honkai", "star_rail", "himeko", "kafka", "bronya",
                          "seele", "silver_wolf", "asta", "march", "dan_heng",
                          "jing_yuan", "clara", "sushang", "bailu", "luocha",
                          "blade", "firefly", "robin", "acheron", "black_swan",
                          "sparkle", "ruan_mei", "topaz", "jingliu", "fu_xuan",
                          "lynx", "hook", "natasha", "gepard", "serval",
                          "sampo", "pela", "qingque", "tingyun", "guinaifen",
                          "xueyi", "dr_ratio", "aventurine", "gallagher",
                          "misha", "boothill", "jade", "yunli", "jiaoqiu",
                          "feixiao", "lingsha", "moze", "sunday", "agalea",
                          "castorice", "anaxa", "hyacine", "cyrene",
                          "screwllum", "penacony", "hi3", "herrscher"],
    "Blue Archive": ["blue_archive", "hoshino", "serika", "shiroko", "hifumi",
                     "ayane", "nonomi", "aru", "mutsuki", "kayoko", "haruka",
                     "izumi", "junko", "yuzu", "midori", "momoi", "hasumi",
                     "yuuka", "chise", "noa", "rio", "himari", "key", "arona",
                     "plana", "mika", "satsuki", "toki", "neru", "karin",
                     "akane", "asuna", "izuna", "tsubaki", "mashiro", "saori",
                     "arito", "misaki", "hime", "azusa", "hanako", "koharu",
                     "hina", "iori", "ako", "shigure", "wakamo", "kaede",
                     "kaya", "iroha", "nagisa", "moe", "shizuko", "kirino",
                     "saya", "suzumi", "chinatsu", "kivotos", "schale",
                     "abydos", "gehenna", "trinity", "millennium"],
    "Azur Lane": ["azur_lane", "enterprise", "akagi", "kaga", "taihou",
                  "belfast", "atago", "takao", "prinz_eugen", "bismarck",
                  "tirpitz", "hood", "warspite", "dido", "sirius", "unicorn",
                  "illustrious", "queen_elizabeth", "z23", "laffey", "javelin",
                  "ayanami", "akashi", "amagi", "ryuuhou", "shinano",
                  "new_jersey", "nj", "anchorage", "agir", "friedrich",
                  "fdg", "u_47", "u47", "laffey", "saratoga", "lexington",
                  "yorktown", "enterprise", "hornet", "akagi", "kaga"],
    "NIKKE": ["nikke", "marian", "modernia", "scarlet", "noir", "blanc",
              "rupee", "diesel", "laplace", "brid", "centi", "doro", "liter",
              "volume", "signal", "noise", "frima", "snow_white", "rapunzel",
              "red_hood", "cinderella", "grave", "tia", "naga", "anis",
              "rapture", "goddess", "pilgrim", "missilis", "tetra", "elysion"],
    "Fate": ["fate", "saber", "artoria", "altria", "tohsaka", "gilgamesh",
             "emiya", "archer", "lancer", "rider", "caster", "berserker",
             "assassin", "jeanne", "jalter", "mash", "mashu", "mordred",
             "nitocris", "ereshkigal", "ishtar", "astarte", "bb", "meltryllis",
             "passionlip", "kama", "kiara", "tamamo", "scathach", "semiramis",
             "cleopatra", "seraph", "chaldea", "sakura", "matou", "medusa",
             "medea", "cu_chulainn", "hercules", "astolfo", "frankenstein",
             "jeanne_darc", "okita", "souji", "nobu", "oda_nobunaga",
             "moriarty", "holmes", "merlin", "vivian", "lancelot", "gawain",
             "tristan", "bedivere", "morgan", "barghest", "baobhan_sith",
             "melusine", "percival", "habertrot", "caren", "amakusa",
             "semiramis", "fate_grand_order", "fgo"],
    "hololive": ["hololive", "gura", "gawr", "amelia", "calliope", "mori",
                 "ina", "kiara", "takanashi", "rushia", "pekora", "usada",
                 "marine", "houshou", "noel", "shion", "murasaki", "ayame",
                 "nakiri", "suisei", "sui", "miko", "sakura", "fubuki",
                 "shirakami", "matsuri", "natsuiro", "aqua", "minato",
                 "subaru", "oozora", "korone", "inugami", "okayu", "botan",
                 "shishiro", "lamy", "yukihana", "nene", "momosuzu", "polka",
                 "laplus", "lui", "koyori", "chloe", "iroha", "sakamata",
                 "kazama", "fuwa", "ao", "raora", "hiodoshi", "juufuutei",
                 "koseki", "bijou", "shiori", "nerissa", "fuwawa", "mococo",
                 "baelz", "hakos", "nanashi", "mumei", "ceres", "fauna",
                 "ouro", "kronii", "irys", "sana", "tsukumo", "mumei",
                 "council", "myth", "promise", "advent", "reGLOSS", "dev_is",
                 "holoX", "hololive_en", "hololive_jp", "hololive_id"],
    "Arknights": ["arknights", "amiya", "ch'en", "chen", "exusiai", "texas",
                  "lappland", "saria", "silverash", "silver_ash", "schwarz",
                  "specter", "skadi", "kal'tsit", "kaltsit", "mudrock",
                  "rosmontis", "suzuran", "thorns", "mountain", "horn",
                  "nearl", "blemishine", "shining", "nightingale", "pramanix",
                  "platinum", "blue_poison", "gravel", "mayer", "podenco",
                  "utage", "bibeak", "cutter", "surtr", "eunectes",
                  "passenger", "weedy", "mizuki", "ling", "dusk", "nian",
                  "saga", "fartooth", "fiammetta", "goldenglow", "holungday",
                  "irin", "hopper", "munar", "qiu_bai", "rhodes", "island",
                  "lungmen", "reunion", "originium", "rhine_lab"],
    "Evangelion": ["evangelion", "eva", "asuka", "langley", "ayanami",
                   "shinji", "ikari", "misato", "katsuragi", "kaworu",
                   "nagisa", "rei", "nerv", "seele", "unit_01", "unit_02",
                   "unit_00"],
    "Spy x Family": ["spy_x_family", "spy_family", "anya", "forger", "yor",
                     "loid", "twilight", "bond", "franky", "yuri", "daybreak",
                     "fiona", "nightfall", "waku_waku", "peanut"],
    "One Piece": ["one_piece", "nami", "nico_robin", "robin", "boa", "hancock",
                  "perona", "hina", "vivi", "yamato", "carrot", "shirahoshi",
                  "reiju", "smoothie", "mihawk", "zoro", "roronoa", "sanji",
                  "luffy", "monkey_d", "ace", "portgas", "sabo", "law",
                  "traffy", "trafalgar", "shanks", "buggy", "chopper",
                  "tony_tony", "franky", "brook", "jinbe", "straw_hat",
                  "strawhat", "grand_line", "wano", "dressrosa"],
    "Naruto": ["naruto", "sasuke", "sakura_haruno", "hinata", "kakashi",
               "itachi", "gaara", "tsunade", "kushina", "ino", "tenten",
               "temari", "haku", "kiba", "shino", "neji", "rock_lee",
               "orochimaru", "jiraiya", "minato", "obito", "madara", "pain",
               "nagato", "konan", "kisame", "deidara", "sasori", "hidan",
               "kakuzu", "zetsu", "shikamaru", "sai", "yamato", "kurenai",
               "asuma", "guy", "might_guy", "lee", "tenten", "ino",
               "shino", "kiba", "akamaru", "shippuden", "konoha",
               "hidden_leaf", "uchiha", "uzumaki", "hyuga", "hatake",
               "namikaze", "senju", "akatsuki"],
    "Demon Slayer": ["demon_slayer", "kimetsu", "tanjiro", "nezuko", "zenitsu",
                     "inosuke", "giyu", "tomioka", "shinobu", "kocho",
                     "rengoku", "kyojuro", "mitsuri", "kanroji", "tengen",
                     "uzui", "obanai", "iguro", "sanemi", "shinazugawa",
                     "gyomei", "himejima", "muichiro", "tokito", "kanao",
                     "tsuyuri", "akaza", "daki", "gyutaro", "kokushibo",
                     "muzan", "yoriichi", "tamayo", "ushui", "hashira",
                     "demon_slayer_corps", "slayer", "nichirin"],
    "Konosuba": ["konosuba", "megumin", "aqua", "darkness", "lalatina",
                 "kazuma", "sato", "wiz", "yunyun", "eris", "chomusuke",
                 "vanir", "crimson_demon", "explosion"],
    "Re:Zero": ["re_zero", "rezero", "rem", "ram", "emilia", "subaru",
                "natsuki", "beatrice", "roswaal", "echidna", "satella",
                "frederica", "garfiel", "otto", "felix", "puck", "elza",
                "meili", "petra", "reinhard", "julius", "crusch", "ferris",
                "fels", "lugunica"],
    "Kaguya-sama": ["kaguya", "shinomiya", "hayasaka", "chika", "fujiwara",
                    "miyuki", "shirogane", "ishigami", "miko", "iino",
                    "kei", "karen", "erika", "osaragi", "kashiwagi",
                    "kaguya_sama", "love_is_war"],
    "Oshi no Ko": ["oshi_no_ko", "hoshino", "aqua", "ruby", "kana", "arima",
                   "akane", "kurokawa", "memcho", "meme", "melt", "piyeon",
                   "ai_hoshino", "ichigo", "sarina", "gou", "b_komachi",
                   "sweet_today"],
    "Mob Psycho": ["mob_psycho", "mob", "reigen", "tome", "dimple", "teruki",
                   "serizawa", "rika", "shigeo", "kageyama", "psycho",
                   "claw", "body_improvement"],
    "Made in Abyss": ["made_in_abyss", "riko", "reg", "nanachi", "bondrewd",
                      "mitty", "faputa", "prushka", "ozen", "lyza",
                      "abyss", "hollow", "narehate"],
    "Dorohedoro": ["dorohedoro", "caiman", "nikaido", "noi", "shin",
                   "ebisu", "en", "chidaruma", "hole", "kai", "fujita",
                   "matsumura", "asuka", "kasukabe"],
    "Zelda": ["zelda", "link", "ganon", "ganondorf", "midna", "sidon",
              "mipha", "revali", "urbosa", "daruk", "ruto", "saria",
              "navi", "fi", "tetra", "zant", "skull_kid", "majora",
              "hyrule", "hylian", "gerudo", "zora", "goron", "rito",
              "kokiri", "sheikah", "triforce", "master_sword",
              "breath_of_the_wild", "tears_of_the_kingdom", "botw", "totk"],
    "Pokémon": ["pokemon", "pokémon", "pikachu", "eevee", "charmander",
                "squirtle", "bulbasaur", "jigglypuff", "snorlax", "gengar",
                "mewtwo", "mew", "lucario", "greninja", "gardevoir",
                "lillie", "serena", "dawn", "misty", "cynthia", "nessa",
                "marnie", "floragato", "litten", "rowlet", "popplio",
                "scorbunny", "sobble", "grookey", "fuecoco", "sprigatito",
                "quaxly", "meowscarada", "skeledirge", "charizard",
                "blastoise", "venusaur", "garchomp", "glimmora", "tinkaton",
                "pokedex", "kanto", "johto", "hoenn", "sinnoh", "unova",
                "kalos", "alola", "galar", "paldea"],
    "League of Legends": ["league", "lol", "jinx", "ahri", "lux", "akali",
                          "katarina", "ashe", "miss_fortune", "morgana",
                          "syndra", "sona", "seraphine", "yuumi", "zoe",
                          "neeko", "qiyana", "sett", "aphelios", "senna",
                          "lissandra", "leona", "diana", "caitlyn", "vi",
                          "powder", "ekko", "jayce", "viktor", "heimerdinger",
                          "ziggs", "teemo", "fizz", "nami", "janna", "soraka",
                          "lulu", "karma", "irelia", "camille", "fiora",
                          "riven", "yasuo", "yone", "zed", "darius", "garen",
                          "aatrox", "kayn", "mordekaiser", "runeterra",
                          "arcane", "piltover", "zaun"],
    "Valorant": ["valorant", "jett", "neon", "phoenix", "raze", "breach",
                 "sova", "cypher", "killjoy", "viper", "omen", "brimstone",
                 "sage", "reyna", "yoru", "astra", "kayo", "chamber",
                 "fade", "harbor", "gekko", "deadlock", "iso", "clove",
                 "vyse", "tejo", "waylay", "radiant", "duelist", "sentinel",
                 "controller", "initiator"],
    "Overwatch": ["overwatch", "dva", "d.va", "mercy", "tracer", "widowmaker",
                  "widow", "sombra", "mei", "symmetra", "zarya", "brigitte",
                  "moira", "ana", "ashe", "echo", "kiriko", "sojourn",
                  "junker_queen", "ramattra", "lifeweaver", "illari", "mauga",
                  "venture", "juno", "winston", "reinhardt", "hanzo",
                  "genji", "mccree", "cassidy", "reaper", "roadhog",
                  "junkrat", "bastion", "torbjorn", "orisa", "sigma",
                  "zenyatta", "lucio", "brigitte", "tank", "support"],
    "Cyberpunk 2077": ["cyberpunk_2077", "judy", "alvarez", "panam", "palmer",
                       "river", "ward", "kerry", "eurodyne", "v", "jackie",
                       "welles", "misty", "olszewski", "rebecca", "lucy",
                       "david", "martinez", "kiwi", "falke", "edgerunners",
                       "alt", "cunningham", "rogue",
                       "amendiares", "silverhand", "johnny", "flathead",
                       "braindance", "netrunner", "mercenary"],
    "Dark Souls": ["dark_souls", "solaire", "gwynevere", "gwyndolin",
                   "artorias", "sif", "orian", "gwyn", "manus", "faraam",
                   "alva", "lothric", "lorian", "soul_of_cinder",
                   "nameless_king", "pontiff", "sulyvahn", "yhorm",
                   "aldrich", "abyss_watchers", "dancer", "vordt",
                   "gundyr", "firelink", "anor_londo", "bonfire", "estus"],
    "Elden Ring": ["elden_ring", "malenia", "ranni", "rennala", "melina",
                   "marika", "radagon", "godrick", "godfrey", "morgott",
                   "mohg", "radahn", "millicent", "fia", "latenna",
                   "nepheli", "roxanne", "sellen", "sorceress", "tanith",
                   "rykard", "godskin", "tarnished", "lands_between",
                   "erdtree", "finger", "graceless"],
    "Bloodborne": ["bloodborne", "lady_maria", "eileen", "the_crow", "doll",
                   "amelia", "ludwig", "gascoigne", "gherman", "gehrman",
                   "ebrietas", "rom", "amygdala", "micolash", "wet_nurse",
                   "hunter", "yharnam", "old_hunters", "moon_presence"],
    "Genshin/HSR misc": [],  # placeholder never matched
}

# Drop empty entries
SERIES = {k: v for k, v in SERIES.items() if v}

# Drop the generic genre word so cyberpunk-aesthetic wallpapers don't
# become "Cyberpunk 2077" series matches (specific tokens still work).
SERIES["Cyberpunk 2077"] = [a for a in SERIES["Cyberpunk 2077"] if a != "cyberpunk"]
# "night_city" is a generic aesthetic phrase → keep it out of the series.
SERIES["Cyberpunk 2077"] = [a for a in SERIES["Cyberpunk 2077"] if a != "night_city"]

# ---------------------------------------------------------------------------
# Characters: character name -> (series, [alias phrases])
# Aliases listed here also guarantee the series match.
# ---------------------------------------------------------------------------
CHARACTERS = {
    # Sonic
    "Tails": ("Sonic", ["tails", "miles_prower", "tails_doll", "tails_skye"]),
    "Sonic": ("Sonic", ["sonic"]),
    "Knuckles": ("Sonic", ["knuckles"]),
    "Shadow": ("Sonic", ["shadow"]),
    "Amy": ("Sonic", ["amy_rose", "amy"]),
    "Rouge": ("Sonic", ["rouge"]),
    "Silver": ("Sonic", ["silver_the_hedgehog", "silver"]),
    "Blaze": ("Sonic", ["blaze"]),
    "Cream": ("Sonic", ["cream_the_rabbit", "cream"]),
    "Dr. Eggman": ("Sonic", ["eggman"]),
    "Metal Sonic": ("Sonic", ["metal_sonic"]),
    # Jujutsu Kaisen
    "Gojo Satoru": ("Jujutsu Kaisen", ["gojo", "satoru_gojo", "satoru"]),
    "Sukuna": ("Jujutsu Kaisen", ["sukuna"]),
    "Yuji Itadori": ("Jujutsu Kaisen", ["itadori", "yuji", "yuuji"]),
    "Megumi Fushiguro": ("Jujutsu Kaisen", ["megumi", "fushiguro"]),
    "Nobara Kugisaki": ("Jujutsu Kaisen", ["nobara", "kugisaki"]),
    "Suguru Geto": ("Jujutsu Kaisen", ["geto", "suguru_geto"]),
    "Toji Fushiguro": ("Jujutsu Kaisen", ["toji"]),
    "Yuta Okkotsu": ("Jujutsu Kaisen", ["yuta", "okkotsu"]),
    "Maki Zenin": ("Jujutsu Kaisen", ["maki_zenin"]),
    "Kento Nanami": ("Jujutsu Kaisen", ["nanami", "kento_nanami"]),
    "Mahito": ("Jujutsu Kaisen", ["mahito"]),
    "Choso": ("Jujutsu Kaisen", ["choso"]),
    "Rika": ("Jujutsu Kaisen", ["rika"]),
    # Chainsaw Man
    "Denji": ("Chainsaw Man", ["denji"]),
    "Makima": ("Chainsaw Man", ["makima"]),
    "Power": ("Chainsaw Man", ["power"]),
    "Pochita": ("Chainsaw Man", ["pochita"]),
    "Aki Hayakawa": ("Chainsaw Man", ["aki_hayakawa", "hayakawa"]),
    "Reze": ("Chainsaw Man", ["reze"]),
    "Kobeni": ("Chainsaw Man", ["kobeni"]),
    "Himeno": ("Chainsaw Man", ["himeno"]),
    "Kishibe": ("Chainsaw Man", ["kishibe"]),
    "Quanxi": ("Chainsaw Man", ["quanxi"]),
    "Asa Mitaka": ("Chainsaw Man", ["asa_mitaka", "mitaka"]),
    "Yoru": ("Chainsaw Man", ["yoru"]),
    "Fami": ("Chainsaw Man", ["fami"]),
    "Nayuta": ("Chainsaw Man", ["nayuta"]),
    # Vocaloid
    "Hatsune Miku": ("Vocaloid", ["hatsune_miku", "miku"]),
    "Kagamine Rin": ("Vocaloid", ["kagamine_rin", "rin"]),
    "Kagamine Len": ("Vocaloid", ["kagamine_len", "len"]),
    "Megurine Luka": ("Vocaloid", ["megurine_luka", "luka"]),
    "MEIKO": ("Vocaloid", ["meiko"]),
    "KAITO": ("Vocaloid", ["kaito"]),
    "GUMI": ("Vocaloid", ["gumi"]),
    # Touhou
    "Reimu Hakurei": ("Touhou", ["reimu", "hakurei"]),
    "Marisa Kirisame": ("Touhou", ["marisa", "kirisame"]),
    "Cirno": ("Touhou", ["cirno"]),
    "Remilia Scarlet": ("Touhou", ["remilia"]),
    "Flandre Scarlet": ("Touhou", ["flandre"]),
    "Sakuya Izayoi": ("Touhou", ["sakuya", "izayoi"]),
    "Youmu Konpaku": ("Touhou", ["youmu"]),
    "Yukari Yakumo": ("Touhou", ["yukari", "yakumo"]),
    "Koishi Komeiji": ("Touhou", ["koishi"]),
    "Satori Komeiji": ("Touhou", ["satori"]),
    "Patchouli Knowledge": ("Touhou", ["patchouli", "knowledge"]),
    "Alice Margatroid": ("Touhou", ["alice", "margatroid"]),
    "Yuuka Kazami": ("Touhou", ["yuuka", "kazami"]),
    "Yuyuko Saigyouji": ("Touhou", ["yuyuko", "saigyouji"]),
    "Sanae Kochiya": ("Touhou", ["sanae", "kochiya"]),
    "Aya Shameimaru": ("Touhou", ["aya", "shameimaru"]),
    "Nitori Kawashiro": ("Touhou", ["nitori", "kawashiro"]),
    "Chen": ("Touhou", ["chen"]),
    "Ran Yakumo": ("Touhou", ["ran"]),
    # NieR
    "2B": ("NieR", ["2b"]),
    "A2": ("NieR", ["a2"]),
    "9S": ("NieR", ["9s"]),
    "Kainé": ("NieR", ["kaine"]),
    "Emil": ("NieR", ["emil"]),
    "Devola & Popola": ("NieR", ["devola", "popola"]),
    # Genshin
    "Nahida": ("Genshin Impact", ["nahida"]),
    "Raiden Shogun": ("Genshin Impact", ["raiden"]),
    "Hu Tao": ("Genshin Impact", ["hutao", "hu_tao"]),
    "Ganyu": ("Genshin Impact", ["ganyu"]),
    "Kamisato Ayaka": ("Genshin Impact", ["ayaka"]),
    "Kamisato Ayato": ("Genshin Impact", ["ayato"]),
    "Keqing": ("Genshin Impact", ["keqing"]),
    "Fischl": ("Genshin Impact", ["fischl"]),
    "Mona": ("Genshin Impact", ["mona"]),
    "Klee": ("Genshin Impact", ["klee"]),
    "Qiqi": ("Genshin Impact", ["qiqi"]),
    "Xiao": ("Genshin Impact", ["xiao"]),
    "Venti": ("Genshin Impact", ["venti"]),
    "Zhongli": ("Genshin Impact", ["zhongli"]),
    "Eula": ("Genshin Impact", ["eula"]),
    "Shenhe": ("Genshin Impact", ["shenhe"]),
    "Yae Miko": ("Genshin Impact", ["yae"]),
    "Yelan": ("Genshin Impact", ["yelan"]),
    "Nilou": ("Genshin Impact", ["nilou"]),
    "Dehya": ("Genshin Impact", ["dehya"]),
    "Furina": ("Genshin Impact", ["furina"]),
    "Navia": ("Genshin Impact", ["navia"]),
    "Clorinde": ("Genshin Impact", ["clorinde"]),
    "Arlecchino": ("Genshin Impact", ["arleccino", "arlechinno"]),
    "Neuvillette": ("Genshin Impact", ["neuvillette"]),
    "Wriothesley": ("Genshin Impact", ["wriothesley"]),
    "Kokomi": ("Genshin Impact", ["kokomi", "sangonomiya"]),
    "Kazuha": ("Genshin Impact", ["kazuha", "kaedehara"]),
    "Yoimiya": ("Genshin Impact", ["yoimiya"]),
    "Lumine": ("Genshin Impact", ["lumine"]),
    "Paimon": ("Genshin Impact", ["paimon"]),
    "Noelle": ("Genshin Impact", ["noelle"]),
    "Barbara": ("Genshin Impact", ["barbara"]),
    # HSR
    "Himeko": ("Honkai: Star Rail", ["himeko"]),
    "Kafka": ("Honkai: Star Rail", ["kafka"]),
    "Bronya": ("Honkai: Star Rail", ["bronya"]),
    "Seele": ("Honkai: Star Rail", ["seele"]),
    "Silver Wolf": ("Honkai: Star Rail", ["silver_wolf"]),
    "Asta": ("Honkai: Star Rail", ["asta"]),
    "March 7th": ("Honkai: Star Rail", ["march"]),
    "Dan Heng": ("Honkai: Star Rail", ["dan_heng"]),
    "Jing Yuan": ("Honkai: Star Rail", ["jing_yuan"]),
    "Clara": ("Honkai: Star Rail", ["clara"]),
    "Sushang": ("Honkai: Star Rail", ["sushang"]),
    "Bailu": ("Honkai: Star Rail", ["bailu"]),
    "Luocha": ("Honkai: Star Rail", ["luocha"]),
    "Blade": ("Honkai: Star Rail", ["blade"]),
    "Firefly": ("Honkai: Star Rail", ["firefly"]),
    "Robin": ("Honkai: Star Rail", ["robin"]),
    "Acheron": ("Honkai: Star Rail", ["acheron"]),
    "Black Swan": ("Honkai: Star Rail", ["black_swan"]),
    "Sparkle": ("Honkai: Star Rail", ["sparkle"]),
    "Ruan Mei": ("Honkai: Star Rail", ["ruan_mei"]),
    "Topaz": ("Honkai: Star Rail", ["topaz"]),
    "Jingliu": ("Honkai: Star Rail", ["jingliu"]),
    "Fu Xuan": ("Honkai: Star Rail", ["fu_xuan"]),
    "Lynx": ("Honkai: Star Rail", ["lynx"]),
    "Firefly": ("Honkai: Star Rail", ["firefly"]),
    # Blue Archive
    "Hoshino": ("Blue Archive", ["hoshino"]),
    "Serika": ("Blue Archive", ["serika"]),
    "Shiroko": ("Blue Archive", ["shiroko"]),
    "Hifumi": ("Blue Archive", ["hifumi"]),
    "Ayane": ("Blue Archive", ["ayane"]),
    "Nonomi": ("Blue Archive", ["nonomi"]),
    "Aru": ("Blue Archive", ["aru"]),
    "Mutsuki": ("Blue Archive", ["mutsuki"]),
    "Kayoko": ("Blue Archive", ["kayoko"]),
    "Haruka": ("Blue Archive", ["haruka"]),
    "Junko": ("Blue Archive", ["junko"]),
    "Yuzu": ("Blue Archive", ["yuzu"]),
    "Midori": ("Blue Archive", ["midori"]),
    "Momoi": ("Blue Archive", ["momoi"]),
    "Hasumi": ("Blue Archive", ["hasumi"]),
    "Yuuka": ("Blue Archive", ["yuuka"]),
    "Noa": ("Blue Archive", ["noa"]),
    "Rio": ("Blue Archive", ["rio"]),
    "Mika": ("Blue Archive", ["mika"]),
    "Toki": ("Blue Archive", ["toki"]),
    "Neru": ("Blue Archive", ["neru"]),
    "Karin": ("Blue Archive", ["karin"]),
    "Asuna": ("Blue Archive", ["asuna"]),
    "Izuna": ("Blue Archive", ["izuna"]),
    "Tsubaki": ("Blue Archive", ["tsubaki"]),
    "Mashiro": ("Blue Archive", ["mashiro"]),
    "Saori": ("Blue Archive", ["saori"]),
    "Azusa": ("Blue Archive", ["azusa"]),
    "Hanako": ("Blue Archive", ["hanako"]),
    "Koharu": ("Blue Archive", ["koharu"]),
    "Hina": ("Blue Archive", ["hina"]),
    "Iori": ("Blue Archive", ["iori"]),
    "Ako": ("Blue Archive", ["ako"]),
    "Wakamo": ("Blue Archive", ["wakamo"]),
    "Iroha": ("Blue Archive", ["iroha"]),
    "Nagisa": ("Blue Archive", ["nagisa"]),
    "Moe": ("Blue Archive", ["moe"]),
    "Shizuko": ("Blue Archive", ["shizuko"]),
    "Kirino": ("Blue Archive", ["kirino"]),
    "Saya": ("Blue Archive", ["saya"]),
    "Suzumi": ("Blue Archive", ["suzumi"]),
    "Chinatsu": ("Blue Archive", ["chinatsu"]),
    # Azur Lane
    "Enterprise": ("Azur Lane", ["enterprise"]),
    "Akagi": ("Azur Lane", ["akagi"]),
    "Kaga": ("Azur Lane", ["kaga"]),
    "Taihou": ("Azur Lane", ["taihou"]),
    "Belfast": ("Azur Lane", ["belfast"]),
    "Atago": ("Azur Lane", ["atago"]),
    "Takao": ("Azur Lane", ["takao"]),
    "Prinz Eugen": ("Azur Lane", ["prinz_eugen"]),
    "Bismarck": ("Azur Lane", ["bismarck"]),
    "Tirpitz": ("Azur Lane", ["tirpitz"]),
    "Hood": ("Azur Lane", ["hood"]),
    "Warspite": ("Azur Lane", ["warspite"]),
    "Dido": ("Azur Lane", ["dido"]),
    "Sirius": ("Azur Lane", ["sirius"]),
    "Unicorn": ("Azur Lane", ["unicorn"]),
    "Illustrious": ("Azur Lane", ["illustrious"]),
    "Shinano": ("Azur Lane", ["shinano"]),
    "New Jersey": ("Azur Lane", ["new_jersey", "nj"]),
    # NIKKE
    "Marian": ("NIKKE", ["marian"]),
    "Modernia": ("NIKKE", ["modernia"]),
    "Scarlet": ("NIKKE", ["scarlet"]),
    "Noir": ("NIKKE", ["noir"]),
    "Blanc": ("NIKKE", ["blanc"]),
    "Rupee": ("NIKKE", ["rupee"]),
    "Laplace": ("NIKKE", ["laplace"]),
    "Cinderella": ("NIKKE", ["cinderella"]),
    "Red Hood": ("NIKKE", ["red_hood"]),
    "Snow White": ("NIKKE", ["snow_white"]),
    "Rapunzel": ("NIKKE", ["rapunzel"]),
    "Anis": ("NIKKE", ["anis"]),
    # Fate
    "Saber": ("Fate", ["saber", "artoria", "altria"]),
    "Rin Tohsaka": ("Fate", ["tohsaka"]),
    "Gilgamesh": ("Fate", ["gilgamesh"]),
    "Emiya": ("Fate", ["emiya"]),
    "Jeanne d'Arc": ("Fate", ["jeanne"]),
    "Mash": ("Fate", ["mash", "mashu"]),
    "Mordred": ("Fate", ["mordred"]),
    "Ishtar": ("Fate", ["ishtar"]),
    "Ereshkigal": ("Fate", ["ereshkigal"]),
    "BB": ("Fate", ["bb"]),
    "Meltryllis": ("Fate", ["meltryllis"]),
    "Kama": ("Fate", ["kama"]),
    "Tamamo": ("Fate", ["tamamo"]),
    "Scathach": ("Fate", ["scathach"]),
    "Astolfo": ("Fate", ["astolfo"]),
    "Nobunaga": ("Fate", ["nobu", "oda_nobunaga"]),
    "Okita": ("Fate", ["okita"]),
    "Morgan": ("Fate", ["morgan"]),
    "Melusine": ("Fate", ["melusine"]),
    # hololive
    "Gawr Gura": ("hololive", ["gura", "gawr"]),
    "Amelia Watson": ("hololive", ["amelia"]),
    "Mori Calliope": ("hololive", ["calliope", "mori"]),
    "Ninomae Ina'nis": ("hololive", ["ina"]),
    "Takanashi Kiara": ("hololive", ["kiara", "takanashi"]),
    "Uruha Rushia": ("hololive", ["rushia"]),
    "Usada Pekora": ("hololive", ["pekora", "usada"]),
    "Houshou Marine": ("hololive", ["marine", "houshou"]),
    "Shirogane Noel": ("hololive", ["noel"]),
    "Murasaki Shion": ("hololive", ["shion", "murasaki"]),
    "Nakiri Ayame": ("hololive", ["ayame", "nakiri"]),
    "Hoshimachi Suisei": ("hololive", ["suisei", "sui"]),
    "Sakura Miko": ("hololive", ["miko", "sakura"]),
    "Shirakami Fubuki": ("hololive", ["fubuki", "shirakami"]),
    "Natsuiro Matsuri": ("hololive", ["matsuri", "natsuiro"]),
    "Minato Aqua": ("hololive", ["aqua", "minato"]),
    "Oozora Subaru": ("hololive", ["subaru", "oozora"]),
    "Inugami Korone": ("hololive", ["korone", "inugami"]),
    "Nekomata Okayu": ("hololive", ["okayu"]),
    "Shishiro Botan": ("hololive", ["botan", "shishiro"]),
    "Yukihana Lamy": ("hololive", ["lamy", "yukihana"]),
    "Momosuzu Nene": ("hololive", ["nene", "momosuzu"]),
    "Omaru Polka": ("hololive", ["polka"]),
    "Laplus Darknesss": ("hololive", ["laplus"]),
    "Sakamata Chloe": ("hololive", ["chloe", "sakamata"]),
    "Hakos Baelz": ("hololive", ["baelz", "hakos"]),
    "Nanashi Mumei": ("hololive", ["mumei", "nanashi"]),
    "Ceres Fauna": ("hololive", ["fauna", "ceres"]),
    "Ouro Kronii": ("hololive", ["kronii", "ouro"]),
    "IRyS": ("hololive", ["irys"]),
    "Tsukumo Sana": ("hololive", ["sana", "tsukumo"]),
    "Koseki Bijou": ("hololive", ["bijou", "koseki"]),
    "Shiori Novella": ("hololive", ["shiori"]),
    "Nerissa Ravencroft": ("hololive", ["nerissa"]),
    "Fuwawa Abyssgard": ("hololive", ["fuwawa"]),
    "Mococo Abyssgard": ("hololive", ["mococo"]),
    # Arknights
    "Amiya": ("Arknights", ["amiya"]),
    "Ch'en": ("Arknights", ["ch'en", "chen"]),
    "Exusiai": ("Arknights", ["exusiai"]),
    "Texas": ("Arknights", ["texas"]),
    "Lappland": ("Arknights", ["lappland"]),
    "Saria": ("Arknights", ["saria"]),
    "SilverAsh": ("Arknights", ["silverash", "silver_ash"]),
    "Schwarz": ("Arknights", ["schwarz"]),
    "Specter": ("Arknights", ["specter"]),
    "Skadi": ("Arknights", ["skadi"]),
    "Kal'tsit": ("Arknights", ["kal'tsit", "kaltsit"]),
    "Mudrock": ("Arknights", ["mudrock"]),
    "Rosmontis": ("Arknights", ["rosmontis"]),
    "Suzuran": ("Arknights", ["suzuran"]),
    "Surtr": ("Arknights", ["surtr"]),
    "Dusk": ("Arknights", ["dusk"]),
    "Nian": ("Arknights", ["nian"]),
    "Ling": ("Arknights", ["ling"]),
    # Evangelion
    "Asuka": ("Evangelion", ["asuka", "langley"]),
    "Rei": ("Evangelion", ["rei", "ayanami"]),
    "Shinji": ("Evangelion", ["shinji", "ikari"]),
    "Misato": ("Evangelion", ["misato", "katsuragi"]),
    "Kaworu": ("Evangelion", ["kaworu", "nagisa"]),
    # Spy x Family
    "Anya Forger": ("Spy x Family", ["anya"]),
    "Yor Forger": ("Spy x Family", ["yor"]),
    "Loid Forger": ("Spy x Family", ["loid", "twilight"]),
    "Bond": ("Spy x Family", ["bond"]),
    "Fiona Frost": ("Spy x Family", ["fiona", "nightfall"]),
    # One Piece
    "Nami": ("One Piece", ["nami"]),
    "Nico Robin": ("One Piece", ["nico_robin", "robin"]),
    "Boa Hancock": ("One Piece", ["boa", "hancock"]),
    "Perona": ("One Piece", ["perona"]),
    "Vivi": ("One Piece", ["vivi"]),
    "Yamato": ("One Piece", ["yamato"]),
    "Carrot": ("One Piece", ["carrot"]),
    "Shirahoshi": ("One Piece", ["shirahoshi"]),
    "Reiju": ("One Piece", ["reiju"]),
    "Smoothie": ("One Piece", ["smoothie"]),
    "Roronoa Zoro": ("One Piece", ["zoro", "roronoa"]),
    "Sanji": ("One Piece", ["sanji"]),
    "Monkey D. Luffy": ("One Piece", ["luffy"]),
    "Ace": ("One Piece", ["ace", "portgas"]),
    "Sabo": ("One Piece", ["sabo"]),
    "Trafalgar Law": ("One Piece", ["law", "trafalgar", "traffy"]),
    # Naruto
    "Naruto": ("Naruto", ["naruto"]),
    "Sasuke": ("Naruto", ["sasuke"]),
    "Sakura Haruno": ("Naruto", ["sakura_haruno"]),
    "Hinata": ("Naruto", ["hinata"]),
    "Kakashi": ("Naruto", ["kakashi", "hatake"]),
    "Itachi": ("Naruto", ["itachi"]),
    "Gaara": ("Naruto", ["gaara"]),
    "Tsunade": ("Naruto", ["tsunade"]),
    "Kushina": ("Naruto", ["kushina"]),
    "Ino": ("Naruto", ["ino"]),
    "Temari": ("Naruto", ["temari"]),
    "Haku": ("Naruto", ["haku"]),
    "Kiba": ("Naruto", ["kiba"]),
    "Neji": ("Naruto", ["neji"]),
    "Rock Lee": ("Naruto", ["rock_lee", "lee"]),
    "Orochimaru": ("Naruto", ["orochimaru"]),
    "Jiraiya": ("Naruto", ["jiraiya"]),
    "Minato": ("Naruto", ["minato", "namikaze"]),
    "Obito": ("Naruto", ["obito"]),
    "Madara": ("Naruto", ["madara"]),
    "Pain": ("Naruto", ["pain", "nagato"]),
    "Konan": ("Naruto", ["konan"]),
    "Shikamaru": ("Naruto", ["shikamaru"]),
    # Demon Slayer
    "Tanjiro": ("Demon Slayer", ["tanjiro"]),
    "Nezuko": ("Demon Slayer", ["nezuko"]),
    "Zenitsu": ("Demon Slayer", ["zenitsu"]),
    "Inosuke": ("Demon Slayer", ["inosuke"]),
    "Giyu Tomioka": ("Demon Slayer", ["giyu", "tomioka"]),
    "Shinobu Kocho": ("Demon Slayer", ["shinobu", "kocho"]),
    "Kyojuro Rengoku": ("Demon Slayer", ["rengoku", "kyojuro"]),
    "Mitsuri Kanroji": ("Demon Slayer", ["mitsuri", "kanroji"]),
    "Tengen Uzui": ("Demon Slayer", ["tengen", "uzui"]),
    "Obanai Iguro": ("Demon Slayer", ["obanai", "iguro"]),
    "Sanemi Shinazugawa": ("Demon Slayer", ["sanemi", "shinazugawa"]),
    "Gyomei Himejima": ("Demon Slayer", ["gyomei", "himejima"]),
    "Muichiro Tokito": ("Demon Slayer", ["muichiro", "tokito"]),
    "Kanao Tsuyuri": ("Demon Slayer", ["kanao", "tsuyuri"]),
    "Akaza": ("Demon Slayer", ["akaza"]),
    "Daki": ("Demon Slayer", ["daki"]),
    "Gyutaro": ("Demon Slayer", ["gyutaro"]),
    "Kokushibo": ("Demon Slayer", ["kokushibo"]),
    "Muzan": ("Demon Slayer", ["muzan"]),
    # Konosuba
    "Megumin": ("Konosuba", ["megumin"]),
    "Aqua": ("Konosuba", ["aqua"]),
    "Darkness": ("Konosuba", ["darkness", "lalatina"]),
    "Kazuma": ("Konosuba", ["kazuma", "sato"]),
    "Wiz": ("Konosuba", ["wiz"]),
    "Yunyun": ("Konosuba", ["yunyun"]),
    "Eris": ("Konosuba", ["eris"]),
    "Chomusuke": ("Konosuba", ["chomusuke"]),
    # Re:Zero
    "Rem": ("Re:Zero", ["rem"]),
    "Ram": ("Re:Zero", ["ram"]),
    "Emilia": ("Re:Zero", ["emilia"]),
    "Subaru": ("Re:Zero", ["subaru", "natsuki"]),
    "Beatrice": ("Re:Zero", ["beatrice"]),
    "Echidna": ("Re:Zero", ["echidna"]),
    "Satella": ("Re:Zero", ["satella"]),
    "Frederica": ("Re:Zero", ["frederica"]),
    "Garfiel": ("Re:Zero", ["garfiel"]),
    "Puck": ("Re:Zero", ["puck"]),
    # Kaguya
    "Kaguya Shinomiya": ("Kaguya-sama", ["kaguya", "shinomiya"]),
    "Chika Fujiwara": ("Kaguya-sama", ["chika", "fujiwara"]),
    "Miyuki Shirogane": ("Kaguya-sama", ["miyuki", "shirogane"]),
    "Ai Hayasaka": ("Kaguya-sama", ["hayasaka"]),
    "Yu Ishigami": ("Kaguya-sama", ["ishigami"]),
    "Miko Iino": ("Kaguya-sama", ["miko", "iino"]),
    # Oshi no Ko
    "Ai Hoshino": ("Oshi no Ko", ["ai_hoshino"]),
    "Ruby Hoshino": ("Oshi no Ko", ["ruby", "hoshino"]),
    "Aqua Hoshino": ("Oshi no Ko", ["aqua"]),
    "Kana Arima": ("Oshi no Ko", ["kana", "arima"]),
    "Akane Kurokawa": ("Oshi no Ko", ["akane", "kurokawa"]),
    "MEMcho": ("Oshi no Ko", ["memcho", "meme"]),
    # Mob Psycho
    "Mob": ("Mob Psycho", ["mob"]),
    "Reigen": ("Mob Psycho", ["reigen"]),
    "Tome": ("Mob Psycho", ["tome"]),
    "Dimple": ("Mob Psycho", ["dimple"]),
    "Teruki": ("Mob Psycho", ["teruki"]),
    "Serizawa": ("Mob Psycho", ["serizawa"]),
    # Made in Abyss
    "Riko": ("Made in Abyss", ["riko"]),
    "Reg": ("Made in Abyss", ["reg"]),
    "Nanachi": ("Made in Abyss", ["nanachi"]),
    "Bondrewd": ("Made in Abyss", ["bondrewd"]),
    "Mitty": ("Made in Abyss", ["mitty"]),
    "Faputa": ("Made in Abyss", ["faputa"]),
    "Prushka": ("Made in Abyss", ["prushka"]),
    # Dorohedoro
    "Caiman": ("Dorohedoro", ["caiman"]),
    "Nikaido": ("Dorohedoro", ["nikaido"]),
    "Noi": ("Dorohedoro", ["noi"]),
    "Shin": ("Dorohedoro", ["shin"]),
    "Ebisu": ("Dorohedoro", ["ebisu"]),
    # Zelda
    "Zelda": ("Zelda", ["zelda"]),
    "Link": ("Zelda", ["link"]),
    "Midna": ("Zelda", ["midna"]),
    "Sidon": ("Zelda", ["sidon"]),
    "Mipha": ("Zelda", ["mipha"]),
    "Revali": ("Zelda", ["revali"]),
    "Urbosa": ("Zelda", ["urbosa"]),
    "Ganondorf": ("Zelda", ["ganon", "ganondorf"]),
    "Skull Kid": ("Zelda", ["skull_kid"]),
    # Pokémon
    "Pikachu": ("Pokémon", ["pikachu"]),
    "Eevee": ("Pokémon", ["eevee"]),
    "Charmander": ("Pokémon", ["charmander"]),
    "Squirtle": ("Pokémon", ["squirtle"]),
    "Bulbasaur": ("Pokémon", ["bulbasaur"]),
    "Jigglypuff": ("Pokémon", ["jigglypuff"]),
    "Snorlax": ("Pokémon", ["snorlax"]),
    "Gengar": ("Pokémon", ["gengar"]),
    "Mewtwo": ("Pokémon", ["mewtwo"]),
    "Lucario": ("Pokémon", ["lucario"]),
    "Greninja": ("Pokémon", ["greninja"]),
    "Gardevoir": ("Pokémon", ["gardevoir"]),
    "Lillie": ("Pokémon", ["lillie"]),
    "Serena": ("Pokémon", ["serena"]),
    "Misty": ("Pokémon", ["misty"]),
    "Cynthia": ("Pokémon", ["cynthia"]),
    # League
    "Jinx": ("League of Legends", ["jinx"]),
    "Ahri": ("League of Legends", ["ahri"]),
    "Lux": ("League of Legends", ["lux"]),
    "Akali": ("League of Legends", ["akali"]),
    "Katarina": ("League of Legends", ["katarina"]),
    "Ashe": ("League of Legends", ["ashe"]),
    "Miss Fortune": ("League of Legends", ["miss_fortune"]),
    "Morgana": ("League of Legends", ["morgana"]),
    "Seraphine": ("League of Legends", ["seraphine"]),
    "Caitlyn": ("League of Legends", ["caitlyn"]),
    "Vi": ("League of Legends", ["vi"]),
    "Irelia": ("League of Legends", ["irelia"]),
    "Riven": ("League of Legends", ["riven"]),
    "Yasuo": ("League of Legends", ["yasuo"]),
    "Yone": ("League of Legends", ["yone"]),
    "Zed": ("League of Legends", ["zed"]),
    # Valorant
    "Jett": ("Valorant", ["jett"]),
    "Neon": ("Valorant", ["neon"]),
    "Raze": ("Valorant", ["raze"]),
    "Sage": ("Valorant", ["sage"]),
    "Reyna": ("Valorant", ["reyna"]),
    "Killjoy": ("Valorant", ["killjoy"]),
    "Viper": ("Valorant", ["viper"]),
    "Omen": ("Valorant", ["omen"]),
    "Sova": ("Valorant", ["sova"]),
    "Cypher": ("Valorant", ["cypher"]),
    "Fade": ("Valorant", ["fade"]),
    "Chamber": ("Valorant", ["chamber"]),
    "Iso": ("Valorant", ["iso"]),
    "Clove": ("Valorant", ["clove"]),
    # Overwatch
    "D.Va": ("Overwatch", ["dva", "d.va"]),
    "Mercy": ("Overwatch", ["mercy"]),
    "Tracer": ("Overwatch", ["tracer"]),
    "Widowmaker": ("Overwatch", ["widowmaker", "widow"]),
    "Sombra": ("Overwatch", ["sombra"]),
    "Mei": ("Overwatch", ["mei"]),
    "Symmetra": ("Overwatch", ["symmetra"]),
    "Zarya": ("Overwatch", ["zarya"]),
    "Brigitte": ("Overwatch", ["brigitte"]),
    "Moira": ("Overwatch", ["moira"]),
    "Ana": ("Overwatch", ["ana"]),
    "Ashe": ("Overwatch", ["ashe"]),
    "Kiriko": ("Overwatch", ["kiriko"]),
    "Sojourn": ("Overwatch", ["sojourn"]),
    "Junker Queen": ("Overwatch", ["junker_queen"]),
    # Cyberpunk
    "Judy Alvarez": ("Cyberpunk 2077", ["judy", "alvarez"]),
    "Panam Palmer": ("Cyberpunk 2077", ["panam", "palmer"]),
    "Rebecca": ("Cyberpunk 2077", ["rebecca"]),
    "Lucy": ("Cyberpunk 2077", ["lucy"]),
    "David Martinez": ("Cyberpunk 2077", ["david", "martinez"]),
    "Kiwi": ("Cyberpunk 2077", ["kiwi"]),
    "Johnny Silverhand": ("Cyberpunk 2077", ["silverhand", "johnny"]),
    "Rogue": ("Cyberpunk 2077", ["rogue"]),
    "Alt Cunningham": ("Cyberpunk 2077", ["alt", "cunningham"]),
    # Souls games
    "Solaire": ("Dark Souls", ["solaire"]),
    "Gwynevere": ("Dark Souls", ["gwynevere"]),
    "Artorias": ("Dark Souls", ["artorias"]),
    "Gwyn": ("Dark Souls", ["gwyn"]),
    "Malenia": ("Elden Ring", ["malenia"]),
    "Ranni": ("Elden Ring", ["ranni"]),
    "Rennala": ("Elden Ring", ["rennala"]),
    "Melina": ("Elden Ring", ["melina"]),
    "Marika": ("Elden Ring", ["marika"]),
    "Radagon": ("Elden Ring", ["radagon"]),
    "Godrick": ("Elden Ring", ["godrick"]),
    "Godfrey": ("Elden Ring", ["godfrey"]),
    "Morgott": ("Elden Ring", ["morgott"]),
    "Mohg": ("Elden Ring", ["mohg"]),
    "Radahn": ("Elden Ring", ["radahn"]),
    "Millicent": ("Elden Ring", ["millicent"]),
    "Fia": ("Elden Ring", ["fia"]),
    "Lady Maria": ("Bloodborne", ["lady_maria"]),
    "Eileen": ("Bloodborne", ["eileen"]),
    "The Doll": ("Bloodborne", ["doll"]),
    "Gehrman": ("Bloodborne", ["gherman", "gehrman"]),
    "Ebrietas": ("Bloodborne", ["ebrietas"]),
}

# Single-token aliases that must NOT match when a negative token is present
# (e.g. "tails" inside "twin_tails", "one_piece" inside "one_piece_swimsuit").
NEGATIVE_TOKENS = {
    "tails": {"twin"},
    "one_piece": {"swimsuit", "bikini"},
    "sonic": {"music", "technology", "audio", "sound", "headphones", "speaker", "wave"},
}

# Characters whose aliases are common words → need a second strong signal.
WEAK_CHARACTER_ALIASES = {
    "power", "v", "ai", "aqua", "rei", "rem", "ram", "mob", "neon", "vi",
    "lucy", "noir", "blanc", "doll", "angel", "nova", "maria", "rose",
    "lily", "sakura", "hana", "maki", "nami", "mika", "mio", "moe",
    "momo", "yui", "yuki", "yuri", "kana", "sora", "silver", "blaze",
    "cream", "rouge", "shadow", "mei", "ana", "sage", "ashe", "scarlet",
    "noi", "shin", "hina", "iori", "ako", "rio", "noa", "saya", "hime",
    "key", "sana", "ling", "ran", "chen", "aya", "alice", "dusk",
    "luna", "star", "sunny", "hood", "red_hood", "misty", "snow_white",
    "law", "robin", "tails", "vector", "panda",
}

# ---------------------------------------------------------------------------
# Feature tags (curated set of common konachan-style tokens)
# ---------------------------------------------------------------------------
FEATURES = [
    # people / count
    "1girl", "2girls", "3girls", "4girls", "5girls", "solo", "multiple_girls",
    "1boy", "2boys", "male", "female", "group", "portrait", "selfie",
    # hair (colors)
    "black_hair", "white_hair", "brown_hair", "blonde_hair", "blond_hair",
    "red_hair", "orange_hair", "pink_hair", "purple_hair", "blue_hair",
    "aqua_hair", "teal_hair", "green_hair", "gray_hair", "grey_hair",
    "silver_hair", "gold_hair", "rainbow_hair", "multicolored_hair",
    "two_tone_hair", "streaked_hair", "ombre_hair",
    # hair (styles)
    "long_hair", "short_hair", "medium_hair", "very_long_hair", "shoulder_length_hair",
    "twin_tails", "twintails", "ponytail", "side_ponytail", "low_ponytail",
    "braid", "braids", "twin_braids", "bun", "hair_bun", "double_bun",
    "odango", "hime_cut", "bob_cut", "blunt_bangs", "bangs", "ahoge",
    "drill_hair", "curly_hair", "wavy_hair", "straight_hair", "messy_hair",
    "wet_hair", "loose_hair", "hair_down", "hair_up", "hair_ornament",
    "hair_ribbon", "hair_clip", "hairpin", "hairband", "hair_flower",
    "hair_bow", "ribbon", "bow", "hair_tie", "hair_scrunchies",
    # eyes
    "red_eyes", "blue_eyes", "green_eyes", "brown_eyes", "purple_eyes",
    "pink_eyes", "orange_eyes", "yellow_eyes", "golden_eyes", "gray_eyes",
    "grey_eyes", "aqua_eyes", "teal_eyes", "black_eyes", "white_eyes",
    "heterochromia", "closed_eyes", "half_closed_eyes", "eye_contact",
    "looking_at_viewer", "looking_away", "looking_back", "glasses",
    "sunglasses", "eyepatch", "contact_lenses", "blush", "fang", "cat_smile",
    "smile", "grin", "open_mouth", "tongue", "blep", "wink", "tears",
    # body / animal traits
    "animal_ears", "cat_ears", "neko", "nekomimi", "fox_ears", "kitsune",
    "rabbit_ears", "dog_ears", "wolf_ears", "bear_ears", "dragon_ears",
    "elf_ears", "pointy_ears", "animal_tail", "cat_tail", "fox_tail",
    "tail", "wings", "angel_wings", "demon_wings", "dragon_wings",
    "bat_wings", "halo", "horns", "demon_horns", "devil_horns", "antenna",
    "catgirl", "doggirl", "foxgirl", "bunnygirl", "kemonomimi", "furry",
    "scales", "fangs", "claws", "paws", "hooves",
    # clothing
    "school_uniform", "sailor_uniform", "blazer", "gakuran", "maid", "maid_outfit",
    "nurse", "waitress", "casual", "hoodie", "sweater", "jacket", "coat",
    "parka", "trenchcoat", "vest", "suit", "tuxedo", "dress", "gown",
    "evening_gown", "ball_gown", "wedding_dress", "kimono", "yukata",
    "qipao", "cheongsam", "hanbok", "sari", "turtleneck", "crop_top",
    "tank_top", "tube_top", "camisole", "bikini", "swimsuit", "one_piece_swimsuit",
    "school_swimsuit", "sports_bra", "lingerie", "underwear", "panties",
    "bra", "stockings", "thigh_highs", "kneehighs", "socks", "pantyhose",
    "tights", "leggings", "garter", "garter_belt", "suspenders", "belt",
    "gloves", "mittens", "arm_warmers", "wristband", "boots", "shoes",
    "sandals", "slippers", "high_heels", "platform_boots", "sneakers",
    "loafers", "barefoot", "bare_shoulders", "midriff", "navel", "see_through",
    "transparent", "wet_clothes", "apron", "scarf", "cloak", "cape",
    "hood", "hat", "cap", "beret", "top_hat", "witch_hat", "santa_hat",
    "party_hat", "crown", "tiara", "mask", "helmet", "visor", "goggles",
    "headphones", "earbuds", "choker", "necklace", "pendant", "earrings",
    "jewelry", "collar", "bell", "ribbon_choker",
    # action / pose
    "sitting", "standing", "lying", "sleeping", "kneeling", "squatting",
    "crouching", "jumping", "running", "walking", "dancing", "singing",
    "playing_guitar", "guitar", "electric_guitar", "bass_guitar", "drums",
    "piano", "microphone", "headphones", "holding", "hand_holding",
    "hug", "cuddle", "embrace", "kiss", "carrying", "piggyback", "selfie",
    "reading", "writing", "drawing", "painting", "cooking", "eating",
    "drinking", "smoking", "smoking_cigarette", "cigarette", "vape",
    "phone", "smartphone", "laptop", "computer", "pc", "gaming", "controller",
    "game_console", "monitor", "keyboard", "mouse",
    # setting / scenery
    "bed", "pillow", "blanket", "couch", "sofa", "table", "desk", "chair",
    "bookshelf", "books", "library", "classroom", "office", "kitchen",
    "bathroom", "bedroom", "living_room", "balcony", "rooftop", "window",
    "door", "fence", "gate", "bridge", "tower", "castle", "palace",
    "mansion", "house", "cottage", "cabin", "tent", "campsite", "camping",
    "campfire", "bonfire", "fireplace", "street", "alley", "city", "cityscape",
    "night_city", "neon_lights", "neon_sign", "streetlight", "lamppost",
    "rain", "raining", "rainbow", "thunder", "lightning", "storm", "snow",
    "snowing", "snowflake", "blizzard", "ice", "frost", "fog", "mist",
    "cloud", "clouds", "cloudy", "sky", "starry_sky", "starry_night",
    "stars", "galaxy", "nebula", "planet", "moon", "full_moon",
    "crescent_moon", "moonlight", "sunset", "sunrise", "dusk", "dawn",
    "twilight", "golden_hour", "blue_hour", "night", "midnight", "day",
    "morning", "afternoon", "evening", "sun", "sunshine", "sunny",
    "forest", "woods", "jungle", "garden", "park", "field", "meadow",
    "grass", "flowers", "flower_field", "cherry_blossom", "cherry_blossoms",
    "sakura", "rose", "roses", "lily", "lilies", "sunflower", "tulip",
    "mountain", "hill", "valley", "cliff", "canyon", "desert", "beach",
    "ocean", "sea", "shore", "coast", "lake", "pond", "river", "stream",
    "waterfall", "harbor", "pier", "dock", "boat", "ship", "sailboat",
    "yacht", "underwater", "pool", "swimming_pool", "hot_spring", "onsen",
    "sauna", "bath", "bathtub", "shower",
    # style / mood / genre
    "dark", "gothic", "lolita", "gothic_lolita", "pastel", "minimalist",
    "vaporwave", "synthwave", "retro", "pixel_art", "pixel", "watercolor",
    "oil_painting", "sketch", "lineart", "ink", "chibi", "cute", "kawaii",
    "elegant", "moe", "aesthetic", "wallpaper", "artwork", "fanart",
    "original", "original_character", "oc", "scenery", "landscape",
    "mecha", "robot", "cyborg", "android", "drone", "armor", "knight",
    "samurai", "ninja", "pirate", "witch", "wizard", "mage", "angel",
    "demon", "devil", "succubus", "vampire", "zombie", "ghost", "spirit",
    "fairy", "elf", "mermaid", "siren", "monster", "creature", "dragon",
    "wolf", "fox", "cat", "dog", "rabbit", "bird", "butterfly", "spider",
    "sword", "katana", "blade", "dagger", "knife", "spear", "lance",
    "axe", "hammer", "bow_and_arrow", "bow", "arrow", "crossbow", "gun",
    "pistol", "rifle", "shotgun", "sniper_rifle", "smg", "machine_gun",
    "cannon", "rocket_launcher", "grenade", "bomb", "missile", "tank",
    "vehicle", "car", "sports_car", "bike", "motorcycle", "train", "plane",
    "airplane", "jet", "fighter_jet", "helicopter", "spaceship", "rocket",
    "satellite", "space", "astronaut", "cosmonaut", "space_suit",
    "science_fiction", "scifi", "cyberpunk", "steampunk", "fantasy",
    "magic", "spell", "energy", "fire", "flame", "smoke", "explosion",
    "battle", "fight", "combat", "war", "blood", "gore", "dark_fantasy",
    "halloween", "pumpkin", "jack_o_lantern", "spooky", "christmas", "santa",
    "xmas", "snowman", "gift", "present", "valentine", "heart", "hearts",
    "birthday", "cake", "candle", "new_year", "fireworks", "festival",
    "parade", "party", "celebration", "music", "song", "concert", "stage",
    "dance", "theater", "cinema", "film", "anime", "manga", "comic",
    "game", "videogame", "rpg", "fps", "racing", "sports", "tennis",
    "soccer", "football", "baseball", "basketball", "volleyball", "gym",
    "fitness", "yoga", "meditation", "sleep", "dream", "nightmare",
    "rainy", "windy", "snowy", "sunny_day", "rainbow", "cloudy_sky",
    "starry", "moonlit", "sunlit", "neon", "glowing", "shiny", "sparkle",
    "sparkles", "glitter", "bokeh", "blur", "depth_of_field", "close_up",
    "closeup", "macro", "wide_shot", "aerial_view", "birds_eye_view",
    "high_angle", "low_angle", "overhead", "panorama", "panoramic",
    "reflection", "mirror", "silhouette", "backlight", "backlit",
    "cinematic", "dramatic", "moody", "warm", "cool", "vibrant", "muted",
    "monochrome", "black_and_white", "sepia", "duotone", "gradient",
    "colorful", "pastel_colors", "dark_theme", "light_theme",
]

# Tokens that are pure noise and should never become tags
NOISE_TOKENS = {
    "anime", "jpeg", "png", "jpg", "webp", "gif", "mp4", "webm", "mov",
    "art", "artwork", "wallpaper", "wallpapers", "image", "img", "pic",
    "hd", "uhd", "4k", "8k", "2k", "res", "resolution", "render", "rendered",
    "3d", "2d", "cg", "cgi", "official", "fan", "fanart", "commission",
    "original", "oc", "drawing", "sketch", "scan", "photo", "photograph",
    "source", "unknown", "sample", "test", "preview", "thumb", "thumbnail",
    "wallpaper_engine", "we", "steam", "konachan", "danbooru", "gelbooru",
    "yandere", "safebooru", "zerochan", "pixiv", "twitter", "deviantart",
    "newgrounds", "reddit", "discord", "v1", "v2", "v3", "v4", "v5",
    "ver", "version", "final", "finished", "complete", "fix", "fixed",
    "edit", "edited", "color", "colored", "colour", "clean", "cleaned",
    "upscaled", "ai", "aigenerated", "generated", "stable_diffusion",
    "midjourney", "novelai", "niji", "dall", "e", "xl", "v", "wip",
    "concept", "concept_art", "key", "visual", "mv", "pv", "op", "ed",
    "ost", "bga", "bg", "foreground", "background", "crop", "cropped",
    "uncropped", "crop_top", "object", "subject", "character_sheet",
    "reference", "ref", "sheet", "base", "template", "blank", "empty",
    "unknown_artist", "unknown", "artist", "author", "by", "from", "via",
    "the", "and", "with", "for", "of", "in", "on", "at", "no", "not",
    "very", "more", "most", "all", "some", "one", "two", "three", "four",
    "five", "new", "old", "big", "small", "large", "tiny", "huge",
}

# ---------------------------------------------------------------------------
# Implementation
# ---------------------------------------------------------------------------

def _normalize(name: str) -> str:
    return name.lower().replace("-", "_").replace(" ", "_")


def _split_tokens(name: str) -> set:
    import re
    tokens = set(re.split(r"[^a-z0-9]+", name.lower()))
    tokens.discard("")
    return tokens


def _phrase_present(phrase: str, tokens: set, raw: str) -> bool:
    """Match an underscore phrase against tokens (multi-word = all words present)."""
    phrase = phrase.lower().strip("_")
    if not phrase:
        return False
    if "_" in phrase:
        parts = [p for p in phrase.split("_") if p]
        return all(p in tokens for p in parts)
    # single token: honour negative tokens (e.g. tails vs twin_tails)
    neg = NEGATIVE_TOKENS.get(phrase)
    if neg and any(n in tokens for n in neg):
        return False
    return phrase in tokens


def tag_wallpapers(category: str, filename: str) -> dict:
    """Return {"series": [...], "characters": [...], "tags": [...]} for a file."""
    raw = _normalize(filename)
    # strip extension
    if "." in raw:
        raw = raw.rsplit(".", 1)[0]
    # strip category prefix (e.g. "Anime_")
    prefix = category.lower().rstrip("_")
    if raw.startswith(prefix + "_"):
        raw = raw[len(prefix) + 1:]
    elif raw == prefix:
        raw = ""
    tokens = _split_tokens(raw)

    series_found = []
    for series, aliases in SERIES.items():
        hits = [a for a in aliases if _phrase_present(a, tokens, raw)]
        if hits:
            # weak-only match (common words) needs >=2 weak hits OR a strong hit
            strong_hits = [a for a in hits if a not in WEAK_CHARACTER_ALIASES]
            weak_hits = [a for a in hits if a in WEAK_CHARACTER_ALIASES]
            if strong_hits or len(weak_hits) >= 2:
                series_found.append(series)

    characters_found = []
    for char_name, (series, aliases) in CHARACTERS.items():
        hits = [a for a in aliases if _phrase_present(a, tokens, raw)]
        if not hits:
            continue
        if any(a in WEAK_CHARACTER_ALIASES for a in hits) and not any(a not in WEAK_CHARACTER_ALIASES for a in hits):
            # weak-only: require the series to already be confirmed
            if series not in series_found:
                continue
        characters_found.append(char_name)
        if series not in series_found:
            series_found.append(series)

    features = []
    for feat in FEATURES:
        if _phrase_present(feat, tokens, raw):
            features.append(feat)

    # general adjectives from noise-filtered leftover tokens (limited)
    alias_phrases = {a for al in SERIES.values() for a in al}
    alias_phrases |= {a for _, al in CHARACTERS.values() for a in al}
    alias_tokens = {p for phrase in alias_phrases for p in phrase.split("_")}
    feature_tokens = {p for phrase in features for p in phrase.split("_")}
    leftover = sorted(t for t in tokens if t not in NOISE_TOKENS and len(t) > 2
                      and t not in features and t not in alias_tokens
                      and t not in feature_tokens)
    # keep a few interesting leftovers as tags (they are konachan-style descriptors)
    features += leftover[:6]

    return {
        "series": sorted(set(series_found)),
        "characters": sorted(set(characters_found)),
        "tags": sorted(set(features)),
    }


if __name__ == "__main__":
    import sys
    tests = [
        ("Anime", "Anime_tails_sonic_friends_blue_sky.jpg"),
        ("Anime", "Anime_gojo_satoru_jujutsu_kaisen_dark.png"),
        ("Anime", "Anime_2B_2b_nier_blue_lily.mp4"),
        ("Anime", "Anime_hatsune_miku_long_hair_twintails_vocaloid.jpg"),
        ("Anime", "Anime_makima_chainsaw_man_red_hair.png"),
        ("Anime", "Anime_black_hair_red_eyes_gothic_dress_twintails.png"),
        ("Anime", "Anime_power_pochita_chainsaw_devil.jpg"),
        ("Anime", "Anime_aqua_blue_hair_konosuba_megumin_explosion.png"),
        ("Anime", "Anime_reimu_hakurei_touhou_red_white.png"),
        ("Anime", "Anime_gawr_gura_hololive_shark_hoodie.png"),
        ("Anime", "Anime_jjk_sukuna_fingers_malevolent_shrine.jpg"),
        ("Anime", "Anime_rem_emilia_re_zero_maid.png"),
    ]
    for cat, name in tests:
        print(f"{name}\n  -> {tag_wallpapers(cat, name)}")
    if len(sys.argv) > 1:
        print(tag_wallpapers("Anime", sys.argv[1]))
